version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  db:
    driver: local
  redis:
    driver: local
